### ISSUE TITLE
New contributors guidelines 

### ISSUE THREAD

**Issue by abdul-rehman-2050** [krzdabrowski/android-starter-2022#64]
While this is great for learning and practicing. There must be some tasks related to a good first issue or features for new contributors. Also the contribution guidelines are beginner friendly. If possible some feature list or work to-do list so that someone can contribute and it improves learning journey.

**Comment by krzdabrowski** [comment]
Hey, thanks for your insights.

Unfortunately, this project does not expect to have external contributors, nor it doesn't have a "feature or work to-do list" - it is a sample code for starting a new Android project using concrete technologies and concepts as described in these [two](https://proandroiddev.com/clean-android-multi-module-offline-first-scalable-app-in-2022-including-jetpack-compose-mvi-987ebecbecae) [articles](https://medium.com/codequest/clean-android-multi-module-offline-first-scalable-app-in-2022-part-2-including-compose-ui-e1fd0a0f410e) on Medium 🙂 

My suggestions for you:
- if you want to extend the project by creating a proper app to improve your programming skills - fork the project and work on it. This project goal is to be a template for any further works on forked repositories. See example: [my Currency Adder project](https://github.com/krzdabrowski/android-currency-adder).
- if you see some major backbone functionalities are missing here - fork the project and create a Pull Request to this project subsequently. See example: [adding back navigation feature by external contributor](https://github.com/krzdabrowski/android-starter-2022/pull/20). However, I don't think there's anything crucial missing - otherwise someone would notice it in the last 1.5 year 😅 

Happy coding! 🙂
